package modelo.entidad;
// Generated 18-dic-2017 18:13:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * GnrPost generated by hbm2java
 */
public class GnrPost  implements java.io.Serializable {


     private Integer postId;
     private String postTitle;
     private String postSlug;
     private String postAbstract;
     private String postBody;
     private Date postDate;
     private String postVisible;
     private String postImage;

    public GnrPost() {
    }

    public GnrPost(String postTitle, String postSlug, String postAbstract, String postBody, Date postDate, String postVisible, String postImage) {
       this.postTitle = postTitle;
       this.postSlug = postSlug;
       this.postAbstract = postAbstract;
       this.postBody = postBody;
       this.postDate = postDate;
       this.postVisible = postVisible;
       this.postImage = postImage;
    }
   
    public Integer getPostId() {
        return this.postId;
    }
    
    public void setPostId(Integer postId) {
        this.postId = postId;
    }
    public String getPostTitle() {
        return this.postTitle;
    }
    
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle;
    }
    public String getPostSlug() {
        return this.postSlug;
    }
    
    public void setPostSlug(String postSlug) {
        this.postSlug = postSlug;
    }
    public String getPostAbstract() {
        return this.postAbstract;
    }
    
    public void setPostAbstract(String postAbstract) {
        this.postAbstract = postAbstract;
    }
    public String getPostBody() {
        return this.postBody;
    }
    
    public void setPostBody(String postBody) {
        this.postBody = postBody;
    }
    public Date getPostDate() {
        return this.postDate;
    }
    
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }
    public String getPostVisible() {
        return this.postVisible;
    }
    
    public void setPostVisible(String postVisible) {
        this.postVisible = postVisible;
    }
    public String getPostImage() {
        return this.postImage;
    }
    
    public void setPostImage(String postImage) {
        this.postImage = postImage;
    }

    @Override
    public String toString() {
        return "GnrPost{" + "postId=" + postId + ", postTitle=" + postTitle + ", postSlug=" + postSlug + ", postAbstract=" + postAbstract + ", postBody=" + postBody + ", postDate=" + postDate + ", postVisible=" + postVisible + ", postImage=" + postImage + '}';
    }

}


